### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by BlockChainCaffe** [vpaliy/merklelib#6]
---> generate an audit proof the letter A
proof = tree.get_proof('A')

**Comment by vpaliy** [comment]
What's the error exactly?
And you copied that wrong. It should be hashed before putting in.
`proof = tree.get_proof(hashfunc('A'))`

**Comment by BlockChainCaffe** [comment]
that's the thing! if i use it with the hashfunc it does not work
while it does without. Makes no sense to me but I thought you might want to investigate

**Comment by adipto** [comment]
I faced the same problem, i believe i figured out why tho, in the get proof method 
" if target is None:
      target = mapping.get(hasher.hash_leaf(leaf))"
the return value for hash_leaf() is already a hash value, we don't need to call the hash function again in get proof()

**Comment by PanosChtz** [comment]
@adipto I confirm it as well. Example should be fixed.

**Comment by vpaliy** [comment]
@PanosChtz thanks for reminding me about this. I've merged @boneyard93501 's MR which should fix the problem. 

I'm closing this issue. Let me know if it persists.

**Comment by thapakaazzi** [comment]
above issues is still on 
works without hashfunc('A') while audit prroof
